export const parcours = {
  fr: {
    title: 'Boris Guarisma | Parcours & transmission — Qognito',
    description: 'Découvrez le parcours de Boris Guarisma et l’expérience de terrain qui nourrit les formations et ressources pédagogiques Qognito.',
    label: 'Boris Guarisma · Fondateur de Qognito',
    headline: 'L’expérience de terrain au service de la transmission.',
    introduction: 'Je développe des formations et des ressources pédagogiques pour aider les décideurs à évaluer les usages de l’IA, les professionnels à en comprendre les mécanismes et les établissements à intégrer ces compétences dans leurs enseignements.',
    background: 'Cette activité s’appuie sur plus de vingt-cinq ans d’expérience en télécommunications, en science des données et en intelligence artificielle, ainsi que sur des responsabilités de direction technique et de formation.',
    courses: 'Je découvre les formations',
    contributionLabel: 'Ma démarche pédagogique',
    contributionTitle: 'Ce que cette expérience apporte à vos apprentissages',
    contributions: [
      { title: 'Relier la technique à la décision', text: 'Examiner un besoin, comparer les options et rendre visibles les coûts, les limites et les conditions de réussite. Dans les formations, ces questions permettent d’argumenter un choix et de savoir quand le réexaminer.' },
      { title: 'Comprendre ce que l’on construit', text: 'Expliquer les mécanismes des systèmes d’IA et mettre leur fonctionnement à l’épreuve. Les exercices invitent à examiner les résultats, les erreurs et les protections nécessaires.' },
      { title: 'Transmettre à des publics différents', text: 'Adapter les explications et les exercices aux responsabilités des décideurs, des équipes techniques et des apprenants. Mon expérience de formateur en télécommunications, puis en IA chez Avanade, nourrit cette démarche.' },
    ],
    experienceLabel: 'Quelques repères',
    experienceTitle: 'Un parcours d’ingénierie, de direction et de formation',
    experiences: [
      { date: 'Aujourd’hui', company: 'Qognito', role: 'Développement de formations et de ressources pédagogiques', text: 'Trois parcours complémentaires : SAGA-IA pour la décision et la gouvernance, BOOTAG-IA pour l’ingénierie des agents, REASON-IA pour approfondir les mécanismes du raisonnement et de l’apprentissage.' },
      { date: 'Octobre 2025 – juin 2026', company: 'Qognito', role: 'Consultant indépendant', text: 'Poursuite en indépendant de la mission industrielle engagée chez Ippon Technologies, jusqu’à sa fin en juin 2026.' },
      { date: 'Juin 2024 – septembre 2025', company: 'Ippon Technologies', role: 'CTO / Consultant', text: 'Direction technique de l’agence parisienne, accompagnement des équipes et cadrage de projets d’IA.' },
      { date: 'Mars 2019 – mai 2024', company: 'Avanade', role: 'Practice Lead France — Intelligence Artificielle', text: 'Structuration et pilotage de la practice IA France, accompagnement de projets et formation d’équipes de grands comptes aux usages de l’IA.' },
      { date: 'Septembre 2016 – février 2019', company: 'Capgemini', role: 'Senior Data Scientist', text: 'Conception de solutions de détection d’anomalies et de fraude, et travaux d’innovation industrielle.' },
      { date: 'Avril 2014 – août 2016', company: 'Musicovery', role: 'Data Scientist & Consultant Big Data', text: 'Apprentissage automatique appliqué à la recommandation musicale, graphes de connaissances et évaluation expérimentale.' },
      { date: 'Octobre 1998 – septembre 2013', company: 'Nokia · Nortel · Anite · NET2S · Steria', role: 'Ingénieur télécommunications', text: 'Ingénierie et architecture de réseaux, avant-vente et formation technique. Chez NET2S / Steria, formation certifiée GSM/2G en français, anglais et espagnol.' },
    ],
    missionLabel: 'Une expérience qui nourrit les enseignements',
    missionTitle: 'Du cadrage industriel aux questions de formation',
    mission: 'D’août 2024 à juin 2026, j’ai accompagné le cadrage de projets numériques et d’IA chez un acteur majeur de la filière nucléaire française, d’abord chez Ippon Technologies, puis comme consultant indépendant Qognito.',
    missionLesson: 'Cette expérience nourrit mes enseignements sur l’évaluation des usages, les choix d’architecture, la maîtrise des risques et la préparation des équipes. Elle donne des points d’appui pour travailler les questions de coût, de qualité et de responsabilité.',
    educationTitle: 'Formation académique',
    education: [
      { year: '2014', degree: 'Parcours certifiant Data Science & Big Data', institution: 'CNAM Paris' },
      { year: '2004', degree: 'DEA Traitement des Images et du Signal', institution: 'ENSEA, Cergy' },
      { year: '1998', degree: 'DESS Nouvelles Technologies et Aide à la décision', institution: 'Université de la Méditerranée, Marseille' },
      { year: '1997', degree: 'Maîtrise Systèmes de Télécommunications et Réseaux Informatiques', institution: 'Université Toulouse III' },
    ],
    languagesTitle: 'Trois langues de travail',
    languages: 'Français et anglais courants · Espagnol, langue maternelle.',
    contactTitle: 'Quel enseignement pour votre contexte ?',
    contactText: 'Vous souhaitez vous former, faire progresser votre équipe ou enrichir un cursus existant ? Échangeons sur votre public, les compétences recherchées et les ressources adaptées.',
    schoolText: 'Responsables de MBA et de formations pour décideurs : des sections de SAGA-IA peuvent être proposées comme interventions au sein de vos parcours existants.',
    contactLabel: 'Je présente mon besoin de formation',
    contactSubject: 'Qognito — besoin de formation',
    contactBody: 'Bonjour Boris,\n\nJe souhaite échanger sur un besoin de formation.\nMon contexte (activité, équipe ou cursus) :\nLe public concerné :\nLes compétences recherchées :\nLe format envisagé (parcours, ressources ou intervention ciblée) :\n\nMerci.',
    teaserLabel: 'Parcours & transmission',
    teaserTitle: 'Une expérience de terrain qui nourrit les formations',
    teaserText: 'Découvrez le parcours et la démarche de transmission à l’origine des ressources Qognito.',
    teaserLink: 'Je découvre le parcours de Boris',
  },
  en: {
    title: 'Boris Guarisma | Background & teaching — Qognito',
    description: 'Discover Boris Guarisma’s background and the professional experience behind Qognito courses and learning resources.',
    label: 'Boris Guarisma · Founder of Qognito',
    headline: 'Bringing practical experience to learning.',
    introduction: 'I develop courses and learning resources to help decision-makers assess AI applications, professionals understand how they work, and educational institutions incorporate these skills into their curricula.',
    background: 'This work draws on more than twenty-five years in telecommunications, data science and artificial intelligence, alongside technical leadership and teaching responsibilities.',
    courses: 'Show me the courses',
    contributionLabel: 'My approach to teaching',
    contributionTitle: 'What this experience brings to your learning',
    contributions: [
      { title: 'Connect technology with decisions', text: 'Examine a need, compare options and make costs, limitations and conditions for success explicit. In the courses, these questions help participants justify a decision and recognise when to revisit it.' },
      { title: 'Understand what you build', text: 'Explain how AI systems work and put their behaviour to the test. Exercises encourage participants to examine results, errors and the safeguards required.' },
      { title: 'Teach different audiences', text: 'Adapt explanations and exercises to the responsibilities of decision-makers, technical teams and learners. My experience teaching telecommunications, then AI at Avanade, informs this approach.' },
    ],
    experienceLabel: 'Selected milestones',
    experienceTitle: 'A background in engineering, leadership and teaching',
    experiences: [
      { date: 'Today', company: 'Qognito', role: 'Developing courses and learning resources', text: 'Three complementary courses: SAGA-IA for decisions and governance, BOOTAG-IA for agent engineering, and REASON-IA for a deeper understanding of reasoning and learning mechanisms.' },
      { date: 'October 2025 – June 2026', company: 'Qognito', role: 'Independent consultant', text: 'Continued the industrial assignment begun at Ippon Technologies as an independent consultant, through its completion in June 2026.' },
      { date: 'June 2024 – September 2025', company: 'Ippon Technologies', role: 'CTO / Consultant', text: 'Technical leadership of the Paris branch, support for teams and scoping of AI projects.' },
      { date: 'March 2019 – May 2024', company: 'Avanade', role: 'France Practice Lead — Artificial Intelligence', text: 'Built and led the French AI practice, supported projects and trained enterprise teams in AI applications.' },
      { date: 'September 2016 – February 2019', company: 'Capgemini', role: 'Senior Data Scientist', text: 'Developed anomaly and fraud detection solutions and contributed to industrial innovation projects.' },
      { date: 'April 2014 – August 2016', company: 'Musicovery', role: 'Data Scientist & Big Data Consultant', text: 'Applied machine learning to music recommendation, knowledge graphs and experimental evaluation.' },
      { date: 'October 1998 – September 2013', company: 'Nokia · Nortel · Anite · NET2S · Steria', role: 'Telecommunications engineer', text: 'Network engineering and architecture, pre-sales and technical training. At NET2S / Steria, certified GSM/2G training in French, English and Spanish.' },
    ],
    missionLabel: 'Experience that informs the courses',
    missionTitle: 'From industrial projects to learning questions',
    mission: 'From August 2024 to June 2026, I helped scope digital and AI projects for a major organisation in the French nuclear industry, initially at Ippon Technologies and then as an independent consultant through Qognito.',
    missionLesson: 'This experience informs my teaching on assessing applications, making architectural choices, managing risks and preparing teams. It provides practical reference points for exploring cost, quality and accountability.',
    educationTitle: 'Education',
    education: [
      { year: '2014', degree: 'Data Science & Big Data certification programme', institution: 'CNAM Paris, France' },
      { year: '2004', degree: 'DEA in Image and Signal Processing', institution: 'ENSEA, Cergy, France' },
      { year: '1998', degree: 'DESS in New Technologies and Decision Support', institution: 'Université de la Méditerranée, Marseille, France' },
      { year: '1997', degree: 'Maîtrise in Telecommunication Systems and Computer Networks', institution: 'Université Toulouse III, France' },
    ],
    languagesTitle: 'Three working languages',
    languages: 'Fluent French and English · Native Spanish.',
    contactTitle: 'What learning fits your context?',
    contactText: 'Would you like to develop your skills, train your team or enrich an existing curriculum? Let’s discuss your audience, the skills you want to develop and suitable resources.',
    schoolText: 'For MBA and executive programme leaders, individual SAGA-IA sections can be offered as teaching sessions within your existing programmes.',
    contactLabel: 'Discuss my training needs',
    contactSubject: 'Qognito — training needs',
    contactBody: 'Hello Boris,\n\nI would like to discuss a training need.\nMy context (business, team or curriculum):\nThe intended audience:\nThe skills to develop:\nThe format envisaged (course, resources or a focused session):\n\nThank you.',
    teaserLabel: 'Background & teaching',
    teaserTitle: 'Practical experience that informs the courses',
    teaserText: 'Discover the background and teaching approach behind Qognito learning resources.',
    teaserLink: 'Show me Boris’s background',
  },
  es: {
    title: 'Boris Guarisma | Trayectoria y transmisión de conocimiento — Qognito',
    description: 'Conozca la trayectoria de Boris Guarisma y la experiencia profesional que inspira las formaciones y los recursos didácticos de Qognito.',
    label: 'Boris Guarisma · Fundador de Qognito',
    headline: 'Experiencia práctica al servicio del aprendizaje.',
    introduction: 'Desarrollo formaciones y recursos didácticos para ayudar a quienes toman decisiones a evaluar los usos de la IA, a los profesionales a comprender sus mecanismos y a los centros educativos a integrar estas competencias en sus programas.',
    background: 'Esta actividad se apoya en más de veinticinco años de experiencia en telecomunicaciones, ciencia de datos e inteligencia artificial, así como en responsabilidades de dirección técnica y formación.',
    courses: 'Ver las formaciones',
    contributionLabel: 'Mi enfoque pedagógico',
    contributionTitle: 'Cómo contribuye esta experiencia a su aprendizaje',
    contributions: [
      { title: 'Relacionar la tecnología con la toma de decisiones', text: 'Analizar una necesidad, comparar opciones y hacer visibles los costes, los límites y las condiciones de éxito. En las formaciones, estas preguntas ayudan a argumentar una decisión y a reconocer cuándo conviene revisarla.' },
      { title: 'Comprender lo que se construye', text: 'Explicar los mecanismos de los sistemas de IA y poner su funcionamiento a prueba. Los ejercicios invitan a examinar resultados, errores y las medidas de protección necesarias.' },
      { title: 'Enseñar a públicos diversos', text: 'Adaptar las explicaciones y los ejercicios a las responsabilidades de directivos, equipos técnicos y estudiantes. Mi experiencia como formador en telecomunicaciones y, posteriormente, en IA en Avanade sustenta este enfoque.' },
    ],
    experienceLabel: 'Algunos hitos',
    experienceTitle: 'Trayectoria en ingeniería, dirección y formación',
    experiences: [
      { date: 'Actualidad', company: 'Qognito', role: 'Desarrollo de formaciones y recursos didácticos', text: 'Tres itinerarios complementarios: SAGA-IA para la toma de decisiones y la gobernanza, BOOTAG-IA para la ingeniería de agentes y REASON-IA para profundizar en los mecanismos del razonamiento y el aprendizaje.' },
      { date: 'Octubre de 2025 – junio de 2026', company: 'Qognito', role: 'Consultor independiente', text: 'Continuación como consultor independiente de la misión industrial iniciada en Ippon Technologies, hasta su finalización en junio de 2026.' },
      { date: 'Junio de 2024 – septiembre de 2025', company: 'Ippon Technologies', role: 'CTO / Consultor', text: 'Dirección técnica de la oficina de París, acompañamiento a los equipos y definición del alcance de proyectos de IA.' },
      { date: 'Marzo de 2019 – mayo de 2024', company: 'Avanade', role: 'Responsable de la práctica de IA en Francia', text: 'Creación y dirección de la práctica francesa de IA, acompañamiento de proyectos y formación de equipos de grandes empresas en sus usos.' },
      { date: 'Septiembre de 2016 – febrero de 2019', company: 'Capgemini', role: 'Científico de datos sénior', text: 'Diseño de soluciones para detectar anomalías y fraude, y participación en proyectos de innovación industrial.' },
      { date: 'Abril de 2014 – agosto de 2016', company: 'Musicovery', role: 'Científico de datos y consultor de Big Data', text: 'Aprendizaje automático aplicado a la recomendación musical, grafos de conocimiento y evaluación experimental.' },
      { date: 'Octubre de 1998 – septiembre de 2013', company: 'Nokia · Nortel · Anite · NET2S · Steria', role: 'Ingeniero de telecomunicaciones', text: 'Ingeniería y arquitectura de redes, preventa y formación técnica. En NET2S / Steria, formación certificada GSM/2G en francés, inglés y español.' },
    ],
    missionLabel: 'Experiencia que inspira las formaciones',
    missionTitle: 'De los proyectos industriales a las preguntas de aprendizaje',
    mission: 'De agosto de 2024 a junio de 2026, acompañé la definición del alcance de proyectos digitales y de IA para una organización destacada del sector nuclear francés, primero en Ippon Technologies y después como consultor independiente a través de Qognito.',
    missionLesson: 'Esta experiencia inspira mis contenidos sobre evaluación de usos, decisiones de arquitectura, gestión de riesgos y preparación de equipos. Aporta referencias prácticas para trabajar cuestiones de coste, calidad y responsabilidad.',
    educationTitle: 'Formación académica',
    education: [
      { year: '2014', degree: 'Programa de certificación en Ciencia de Datos y Big Data', institution: 'CNAM París, Francia' },
      { year: '2004', degree: 'DEA en Tratamiento de Imágenes y Señales', institution: 'ENSEA, Cergy, Francia' },
      { year: '1998', degree: 'DESS en Nuevas Tecnologías y Ayuda a la Decisión', institution: 'Université de la Méditerranée, Marsella, Francia' },
      { year: '1997', degree: 'Maîtrise en Sistemas de Telecomunicaciones y Redes Informáticas', institution: 'Université Toulouse III, Francia' },
    ],
    languagesTitle: 'Tres lenguas de trabajo',
    languages: 'Francés e inglés fluidos · Español, lengua materna.',
    contactTitle: '¿Qué formación se adapta a su contexto?',
    contactText: '¿Quiere desarrollar sus competencias, formar a su equipo o enriquecer un plan de estudios existente? Hablemos de su público, las competencias que busca y los recursos adecuados.',
    schoolText: 'Para responsables de MBA y de programas para directivos: algunas secciones de SAGA-IA pueden impartirse como sesiones dentro de programas existentes.',
    contactLabel: 'Explicar mi necesidad de formación',
    contactSubject: 'Qognito — necesidad de formación',
    contactBody: 'Hola, Boris:\n\nMe gustaría hablar sobre una necesidad de formación.\nMi contexto (actividad, equipo o plan de estudios):\nPúblico destinatario:\nCompetencias que se buscan:\nFormato previsto (itinerario, recursos o sesión específica):\n\nGracias.',
    teaserLabel: 'Trayectoria y transmisión de conocimiento',
    teaserTitle: 'Experiencia práctica que inspira las formaciones',
    teaserText: 'Conozca la trayectoria y el enfoque pedagógico que dieron origen a los recursos didácticos de Qognito.',
    teaserLink: 'Ver la trayectoria de Boris',
  },
} as const;
