export const positioning = {
  fr: {
    headline: 'Comprendre l’IA, décider de ses usages, maîtriser sa mise en œuvre.',
    mission: 'Qognito développe des formations et des ressources pédagogiques pour celles et ceux qui décident, conçoivent ou enseignent les usages de l’intelligence artificielle.',
    audiences: 'Dirigeants, équipes métier et techniques, sociétés de conseil, ESN, éditeurs, indépendants et établissements d’enseignement : chaque parcours répond à une responsabilité et à un niveau de pratique.',
    approach: 'Une même exigence guide l’ensemble : comprendre les mécanismes, mettre les choix à l’épreuve et connaître les limites des solutions.',
    explore: 'Découvrir les formations',
    courseLead: 'Décider, construire, approfondir : choisissez votre parcours.',
    courseContext: 'Vous devez évaluer un investissement dans l’IA, développer des agents pour votre activité ou vos clients, ou préparer vos étudiants à ces pratiques ?',
    courseIntroduction: 'Les formations Qognito abordent trois dimensions complémentaires : la décision et la gouvernance, l’ingénierie des agents, et les mécanismes du raisonnement et de l’apprentissage.',
    courseChoice: 'Choisissez le parcours qui correspond à votre besoin et à votre expérience.',
    contactTitle: 'Quel parcours pour votre projet ?',
    contactIntroduction: 'Vous souhaitez vous former, faire progresser votre équipe ou intégrer ces enseignements à un cursus ?',
    contactDescription: 'Présentez-moi votre contexte et les compétences recherchées. Nous pourrons préciser le parcours pertinent, les supports disponibles et les modalités adaptées.',
    contactLabel: 'Échanger sur votre projet',
    contactSubject: 'Qognito — projet de formation',
    contactBody: 'Bonjour Boris,\n\nJe souhaite échanger sur un projet de formation.\nMon contexte (activité, équipe ou cursus) :\nLe public concerné :\nLes compétences recherchées :\nLe parcours envisagé, si connu :\n\nMerci.',
    bootag: {
      label: 'POUR LES PROFILS TECHNIQUES',
      summary: 'Apprenez à construire des agents IA, à les connecter à des outils et à des connaissances, puis à suivre et évaluer leur fonctionnement.',
      audience: 'Pour les développeurs, consultants techniques, ingénieurs et étudiants qui souhaitent comprendre et maîtriser les mécanismes de leurs applications.',
      contactTitle: 'BOOTAG-IA pour vous, votre équipe ou votre cursus',
    },
    reason: {
      label: 'POUR LES PROFILS TECHNIQUES AVANCÉS',
      summary: 'Explorez comment les modèles produisent leurs réponses et comment différentes méthodes peuvent améliorer leurs résultats. Expérimentez le raisonnement, l’évaluation et l’apprentissage par renforcement pour en apprécier les performances et les limites.',
      audience: 'Pour les professionnels de l’IA, équipes R&D, consultants spécialisés et étudiants avancés.',
      contactTitle: 'REASON-IA pour vous, votre équipe ou votre cursus',
    },
  },
  en: {
    headline: 'Understand AI, decide how to use it, and take control of its implementation.',
    mission: 'Qognito develops courses and learning resources for people who make decisions about AI, build AI applications or teach its uses.',
    audiences: 'Business leaders, business and technical teams, consultancies, IT service providers, software companies, independent professionals and educational institutions: each course addresses a specific responsibility and level of practice.',
    approach: 'One principle guides every course: understand the mechanisms, put choices to the test and recognise the limits of each solution.',
    explore: 'Explore the courses',
    courseLead: 'Decide, build, explore: choose your course.',
    courseContext: 'Do you need to assess an AI investment, develop agents for your business or clients, or prepare your students for these practices?',
    courseIntroduction: 'Qognito courses cover three complementary areas: decision-making and governance, agent engineering, and the mechanisms of reasoning and learning.',
    courseChoice: 'Choose the course that matches your needs and experience.',
    contactTitle: 'Which course fits your project?',
    contactIntroduction: 'Are you looking to develop your skills, train your team or incorporate these topics into a curriculum?',
    contactDescription: 'Tell me about your context and the skills you want to develop. We can discuss the relevant course, available materials and suitable arrangements.',
    contactLabel: 'Discuss your project',
    contactSubject: 'Qognito — training project',
    contactBody: 'Hello Boris,\n\nI would like to discuss a training project.\nMy context (business, team or curriculum):\nThe intended audience:\nThe skills to develop:\nThe course of interest, if known:\n\nThank you.',
    bootag: {
      label: 'FOR TECHNICAL PROFESSIONALS & STUDENTS',
      summary: 'Learn to build AI agents, connect them to tools and knowledge, then monitor and evaluate how they work.',
      audience: 'For developers, technical consultants, engineers and students who want to understand and control the mechanisms behind their applications.',
      contactTitle: 'BOOTAG-IA for you, your team or your curriculum',
    },
    reason: {
      label: 'FOR ADVANCED TECHNICAL LEARNERS',
      summary: 'Explore how models produce responses and how different methods can improve their results. Experiment with reasoning, evaluation and reinforcement learning to assess their performance and limitations.',
      audience: 'For AI professionals, R&D teams, specialist consultants and advanced students.',
      contactTitle: 'REASON-IA for you, your team or your curriculum',
    },
  },
} as const;
