export const sagaContent = {
  fr: {
    name: 'SAGA-IA : Stratège en Architecture & Gouvernance des Agents IA',
    subtitle: 'Stratège en Architecture & Gouvernance des Agents IA',
    audienceLabel: 'POUR LES DÉCIDEURS',
    formatLabel: 'À votre rythme ou sur mesure',
    prerequisite: 'Sans prérequis en programmation',
    summary: 'Que déléguer à l’IA, à quel coût et avec quelles limites ? Apprenez à examiner un projet, à comparer les options et à justifier vos décisions. Pour les dirigeants et responsables qui engagent des ressources, de l’activité indépendante au grand groupe.',
    audienceSummary: 'Vous dirigez seul, à deux ou au sein d’un grand groupe ? Apprenez à décider où engager vos ressources, quelles preuves demander et quand revoir votre choix.',
    discover: 'Découvrir SAGA-IA',
    promise: 'Investir dans l’IA avec des décisions que vous pouvez justifier.',
    introduction: 'Que déléguer ? À quel coût ? Avec quelles limites ? SAGA-IA vous aide à examiner un projet, à questionner une proposition et à décider de poursuivre, de réduire le périmètre ou de renoncer.',
    audience: 'Pour les indépendants, les dirigeants d’entreprises de une ou deux personnes, les responsables métier et les directions générales, financières ou informatiques. Aucune compétence en programmation n’est requise.',
    contact: 'Échanger sur votre projet SAGA-IA',
    contactSubject: 'SAGA-IA — supports et interventions',
    contactBody: 'Bonjour Boris,\n\nJe souhaite échanger sur les supports ou les interventions SAGA-IA.\nMon contexte (activité, équipe ou programme de formation) :\nMon besoin :\nLe public concerné :\n\nMerci.',
    institutionTitle: 'Intégrer une section SAGA-IA à votre MBA ou à votre formation de dirigeants',
    institutionAudience: 'Vous êtes responsable d’un MBA, d’un programme d’Executive Education ou d’un cours spécialisé destiné aux décideurs ?',
    institutionDescription: 'Une ou plusieurs sections de SAGA-IA peuvent faire l’objet d’une intervention ciblée au sein du programme que votre établissement propose déjà. Le choix des sections, la profondeur et la durée de l’intervention se définissent avec vous, selon les acquis des participants et les objectifs de votre parcours.',
    institutionExamples: 'Par exemple : examiner une décision de délégation à l’IA ou comparer les coûts complets d’un service. L’intervention s’insère dans votre progression pédagogique.',
    institutionContact: 'Préparer une intervention dans votre programme',
    institutionSubject: 'SAGA-IA — intervention MBA / formation de décideurs',
    institutionBody: 'Bonjour Boris,\n\nJe suis responsable d’un programme et souhaite y intégrer une intervention SAGA-IA.\nÉtablissement et programme existant :\nProfil des participants :\nObjectifs pédagogiques :\nSection(s) ou thème(s) envisagé(s) :\nDurée et calendrier souhaités :\n\nMerci.',
    sectionsTitle: 'Cinq étapes pour décider et garder la maîtrise',
    sectionLabel: 'Section',
    evidenceLabel: 'Comment mettre votre décision à l’épreuve',
    sections: [
      {
        title: 'Choisir ce que l’on délègue',
        objectives: [
          'Comparer la délégation à une solution sans IA et définir les conditions pour poursuivre.',
          'Comprendre pourquoi certaines corrections se répètent avant de choisir un remède.',
        ],
        evidence: 'Une décision argumentée et un diagnostic des reprises : faits, hypothèses, causes possibles et preuves encore manquantes.',
      },
      {
        title: 'Évaluer le coût réel et la viabilité',
        objectives: [
          'Comparer les coûts complets pour une même qualité et un même périmètre de service.',
          'Calculer les conditions de viabilité, y compris dans un scénario défavorable.',
        ],
        evidence: 'Un comparatif chiffré et une décision conditionnelle. Le temps libéré est distingué des économies réellement possibles.',
      },
      {
        title: 'Réutiliser ce qui mérite de l’être',
        objectives: [
          'Choisir ce qui doit devenir une documentation, une procédure, un contrôle ou un programme.',
          'Organiser les essais, les responsables, les versions et le retrait de ces acquis.',
        ],
        evidence: 'Un choix de réutilisation et un plan de suivi, éprouvés sur des situations où la solution doit fonctionner — et où elle ne doit pas s’appliquer.',
      },
      {
        title: 'Fixer les limites d’action de l’IA',
        objectives: [
          'Repérer les dommages possibles liés aux données, aux accès et aux actions autorisées.',
          'Définir les protections et juger les essais de refus, d’approbation et de reprise.',
        ],
        evidence: 'Des exigences vérifiables et une décision qui tient compte des risques restants. Donner une consigne ne suffit pas à limiter une permission.',
      },
      {
        title: 'Déployer progressivement et pouvoir changer de voie',
        objectives: [
          'Fixer les responsabilités, les contrôles qualité et les conditions d’extension ou de suspension.',
          'Évaluer les dépendances et préparer la reprise du service avec une autre solution.',
        ],
        evidence: 'Un plan de déploiement et un exercice de reprise avec coûts et critères de réussite. Un fichier exportable ne suffit pas à garantir la continuité.',
      },
    ],
    methodTitle: 'Apprendre à décider sur des cas concrets',
    method: 'Deux contextes servent de fil conducteur : la veille en entreprise et une activité de une ou deux personnes. Ces cas sont des simulations, sauf observation explicitement documentée. Chaque étape demande de justifier un choix ; mesurer davantage ou arrêter peut être la bonne décision.',
    methodNote: 'Les acquis sont évalués sur les arguments et les preuves présentés. Aucun gain, aucune économie ni conformité d’une offre n’est garanti par le seul suivi du parcours.',
    nextTitle: 'Quel besoin pour vous, votre équipe ou votre programme ?',
    nextDescription: 'Décrivez votre contexte et votre besoin. Nous pourrons préciser les supports disponibles, les sections pertinentes et les modalités d’une éventuelle intervention.',
    availability: 'Parcours en préparation : les deux premières sections sont rédigées. Le syllabus définitif et les supports de présentation restent à finaliser.',
    whitepaperTitle: 'Un premier aperçu avec le livre blanc',
    whitepaperDescription: '« La facture fantôme de l’IA » introduit les sections 1 et 2 : la décision de délégation et le modèle économique. Le parcours complet poursuit ensuite avec les acquis réutilisables, la sécurité et le déploiement.',
    whitepaperLink: 'Découvrir le livre blanc',
  },
  en: {
    name: 'SAGA-IA: AI Agent Architecture & Governance Strategist',
    subtitle: 'AI Agent Architecture & Governance Strategist',
    audienceLabel: 'FOR DECISION-MAKERS',
    formatLabel: 'Self-paced or tailored support',
    prerequisite: 'No programming background required',
    summary: 'What should you delegate to AI, at what cost and within which limits? Learn to assess a project, compare options and justify your decisions. For leaders and managers who commit resources, from independent businesses to large organisations.',
    audienceSummary: 'Running a business alone, with a partner or within a large organisation? Learn where to commit resources, what evidence to request and when to reconsider.',
    discover: 'Explore SAGA-IA',
    promise: 'Invest in AI with decisions you can justify.',
    introduction: 'What should you delegate? At what cost? Within which limits? SAGA-IA helps you assess a project, question a proposal and decide whether to proceed, narrow the scope or stop.',
    audience: 'For independent professionals, owners of one- or two-person businesses, business managers, and executive, finance or IT leaders. No programming skills are required.',
    contact: 'Discuss your SAGA-IA project',
    contactSubject: 'SAGA-IA — learning materials and teaching sessions',
    contactBody: 'Hello Boris,\n\nI would like to discuss SAGA-IA materials or teaching sessions.\nMy context (business, team or education programme):\nMy needs:\nThe intended audience:\n\nThank you.',
    institutionTitle: 'Bring a SAGA-IA section into your MBA or executive programme',
    institutionAudience: 'Do you lead an MBA, an Executive Education programme or a specialist course for decision-makers?',
    institutionDescription: 'One or more SAGA-IA sections can be delivered as a focused teaching session within a programme your institution already offers. We agree on the sections, depth and duration with you, based on participants’ prior knowledge and your programme’s objectives.',
    institutionExamples: 'For example: assess an AI delegation decision or compare the full costs of a service. The session fits into your existing learning sequence.',
    institutionContact: 'Plan a session within your programme',
    institutionSubject: 'SAGA-IA — MBA / executive education session',
    institutionBody: 'Hello Boris,\n\nI lead a programme and would like to incorporate a SAGA-IA teaching session.\nInstitution and existing programme:\nParticipant profiles:\nLearning objectives:\nSections or topics of interest:\nPreferred duration and dates:\n\nThank you.',
    sectionsTitle: 'Five steps to make decisions and retain control',
    sectionLabel: 'Section',
    evidenceLabel: 'How to put your decision to the test',
    sections: [
      {
        title: 'Choose what to delegate',
        objectives: [
          'Compare delegation with an option that does not use AI and set conditions for proceeding.',
          'Understand why corrections recur before choosing a remedy.',
        ],
        evidence: 'A reasoned decision and a diagnosis of rework: facts, assumptions, possible causes and missing evidence.',
      },
      {
        title: 'Assess full costs and viability',
        objectives: [
          'Compare full costs at equivalent quality and service coverage.',
          'Calculate the conditions for viability, including an adverse scenario.',
        ],
        evidence: 'A cost comparison and a conditional decision. Freed capacity is distinguished from savings that can actually be realised.',
      },
      {
        title: 'Reuse what is worth keeping',
        objectives: [
          'Choose what should become documentation, a procedure, a control or a program.',
          'Plan tests, ownership, version management and withdrawal of these reusable assets.',
        ],
        evidence: 'A reuse decision and lifecycle plan, tested against cases where the solution should work and cases where it should not apply.',
      },
      {
        title: 'Set limits on what AI can do',
        objectives: [
          'Identify potential harm involving data, access and permitted actions.',
          'Specify protections and assess tests of refusal, approval and recovery.',
        ],
        evidence: 'Verifiable requirements and a decision accounting for remaining risks. An instruction alone does not restrict an actual permission.',
      },
      {
        title: 'Roll out gradually and keep alternatives open',
        objectives: [
          'Set responsibilities, quality checks and conditions for expansion or suspension.',
          'Assess dependencies and plan how to resume the service with another solution.',
        ],
        evidence: 'A rollout plan and recovery exercise with costs and acceptance criteria. An exportable file alone does not guarantee continuity.',
      },
    ],
    methodTitle: 'Practise decisions through concrete cases',
    method: 'Two contexts run through the course: business intelligence in an organisation and a one- or two-person business. These cases are simulations unless an observation is explicitly documented. Each step requires a justified choice; gathering more evidence or stopping can be the right decision.',
    methodNote: 'Learning is assessed through the reasoning and evidence presented. Taking the course alone does not guarantee gains, savings or the compliance of a product or service.',
    nextTitle: 'What do you, your team or your programme need?',
    nextDescription: 'Describe your context and needs. We can discuss available materials, relevant sections and arrangements for a teaching session.',
    availability: 'Course in preparation: the first two sections have been written. The final syllabus and presentation materials are still being developed.',
    whitepaperTitle: 'Start with the white paper',
    whitepaperDescription: '“La facture fantôme de l’IA” introduces sections 1 and 2: delegation decisions and AI economics. The full course then addresses reusable assets, security and deployment.',
    whitepaperLink: 'Explore the white paper (in French)',
  },
} as const;
