export const whitepaperContent = {
  "fr": {
    "pageTitle": "La facture fantôme de l’IA — Livre blanc Qognito",
    "description": "Supervision humaine, coûts complets, temps réaffecté : examinez les angles morts du ROI de vos projets IA. Un livre blanc pour DG, DAF et DSI.",
    "audience": "LIVRE BLANC · DIRECTIONS GÉNÉRALES, FINANCIÈRES & SI",
    "title": "La facture fantôme de l’IA",
    "lead": "Supervision humaine, coûts complets, temps réellement réaffecté : les trois angles morts du ROI de vos projets IA.",
    "introduction": "Une démonstration impressionnante ne suffit pas à justifier un investissement. Ce livre blanc vous aide à examiner ce que la facture d’API ne montre pas.",
    "download": "Je télécharge le livre blanc",
    "discover": "Je découvre le contenu du livre blanc",
    "coverLabel": "Présentation du livre blanc",
    "benefitsTitle": "Trois questions pour votre prochain comité",
    "question1": "Qui vérifie le résultat ?",
    "answer1": "Rendez visible le travail de relecture, de correction et de supervision que la génération déplace.",
    "question2": "Quel est le coût complet ?",
    "answer2": "Distinguez les dépenses du modèle, l’infrastructure et le travail humain résiduel.",
    "question3": "Que devient le temps gagné ?",
    "answer3": "Évaluez les conditions de réaffectation nécessaires pour produire une valeur économique.",
    "excerptLabel": "EXTRAIT",
    "excerptTitle": "600 € d’API ne sont pas le prix du service",
    "quote": "« Le coût brut de l’inférence face à une masse salariale complète, c’est comparer le prix du kérosène au coût total d’une flotte aérienne. »",
    "example": "Dans le cas pédagogique SAGA, 600 € d’API s’inscrivent dans un coût complet de 16 500 €, dont 12 000 € de travail humain. Ces montants sont des hypothèses de simulation, pas une moyenne observée du marché.",
    "contentsTitle": "Dans le livre blanc",
    "finding": "Le constat :",
    "findingDetail": "le mirage de la délégation totale.",
    "model": "Le modèle :",
    "modelDetail": "les coûts complets et l’impératif de réaffectation.",
    "decision": "La décision :",
    "decisionDetail": "une grille de questions pour examiner votre projet.",
    "authorTitle": "À propos de l’auteur",
    "author": "Boris Guarisma, président de Qognito, accompagne le cadrage et la gouvernance de projets IA. Ce document s’appuie sur les deux sections rédigées du cursus SAGA-IA consacrées au diagnostic et au modèle économique.",
    "preparation": "Le syllabus et les supports de présentation SAGA-IA sont en préparation.",
    "downloadTitle": "Recevez votre accès au PDF",
    "pendingTitle": "Le PDF est en préparation",
    "emailNotice": "Seul l’email est obligatoire. Aucune inscription automatique à une newsletter.",
    "details": "Vos coordonnées",
    "name": "Nom",
    "company": "Entreprise",
    "role": "Fonction",
    "optional": "(facultatif)",
    "privacy": "QOGNITO utilise vos coordonnées pour gérer votre demande et, si vous le souhaitez, vous recontacter. La demande transite par Web3Forms vers notre messagerie.",
    "privacyLink": "Finalités, conservation et exercice de vos droits",
    "nojs": "Activez JavaScript pour utiliser le formulaire, ou demandez le document à",
    "successTitle": "Votre demande a été transmise.",
    "successText": "Vous pouvez maintenant télécharger le livre blanc.",
    "downloadPdf": "Je télécharge mon PDF",
    "followup": "Une question sur votre projet ?",
    "emailQuestion": "Je pose ma question par email",
    "pending": "La version à télécharger sera disponible ici prochainement.",
    "pendingQuestion": "Vous souhaitez échanger sur les coûts cachés de votre projet IA ?",
    "contact": "Je prends contact avec Qognito",
    "contactStatement": "Je souhaite être contacté par Qognito pour échanger sur la rentabilité et la gouvernance de mon projet IA."
  },
  "en": {
    "pageTitle": "The Hidden AI Bill — Qognito White Paper",
    "description": "Human oversight, total costs and reallocated time: examine the blind spots in your AI projects’ ROI. A white paper for CEOs, CFOs and CIOs.",
    "audience": "WHITE PAPER · CEOs, CFOs & CIOs",
    "title": "The Hidden AI Bill",
    "lead": "Human oversight, total costs and time actually reallocated: three blind spots in your AI projects’ ROI.",
    "introduction": "An impressive demo is not enough to justify an investment. This white paper helps you examine what the API bill leaves out.",
    "download": "Get my white paper",
    "discover": "Show me what’s inside",
    "coverLabel": "Cover of the French white paper",
    "benefitsTitle": "Three questions for your next decision meeting",
    "question1": "Who checks the result?",
    "answer1": "Make visible the review, correction and oversight work that AI generation shifts to people.",
    "question2": "What is the total cost?",
    "answer2": "Distinguish model spending, infrastructure costs and the human work that remains.",
    "question3": "What happens to the time saved?",
    "answer3": "Assess how saved time needs to be reallocated to create economic value.",
    "excerptLabel": "EXCERPT · TRANSLATED FROM FRENCH",
    "excerptTitle": "€600 in API costs is not the cost of the service",
    "quote": "“Comparing raw inference costs with a full payroll is like comparing the price of jet fuel with the total cost of an aircraft fleet.”",
    "example": "In the SAGA teaching case, €600 in API costs sits within a total cost of €16,500, including €12,000 in human work. These figures are simulation assumptions, not observed market averages.",
    "contentsTitle": "Inside the white paper",
    "finding": "The finding:",
    "findingDetail": "the illusion of total delegation.",
    "model": "The model:",
    "modelDetail": "total costs and the need to reallocate saved time.",
    "decision": "The decision:",
    "decisionDetail": "a set of questions to assess your project.",
    "authorTitle": "About the author",
    "author": "Boris Guarisma, president of Qognito, supports the scoping and governance of AI projects. This document draws on the two completed sections of the SAGA-IA course covering diagnosis and the economic model.",
    "preparation": "The SAGA-IA syllabus and presentation materials are in preparation.",
    "downloadTitle": "Get access to the PDF",
    "pendingTitle": "The PDF is in preparation",
    "emailNotice": "Only your email address is required. You will not be automatically subscribed to a newsletter.",
    "details": "Your details",
    "name": "Name",
    "company": "Company",
    "role": "Job title",
    "optional": "(optional)",
    "privacy": "QOGNITO uses your details to handle your request and, if you choose, contact you. Your request passes through Web3Forms to our email service.",
    "privacyLink": "Purposes, retention and your rights (in French)",
    "nojs": "Enable JavaScript to use this form, or request the document by emailing",
    "successTitle": "Your request has been submitted.",
    "successText": "You can now download the white paper. The PDF is in French.",
    "downloadPdf": "I'm downloading the PDF",
    "followup": "Have a question about your project?",
    "emailQuestion": "Send my question by email",
    "pending": "The downloadable version will be available here soon.",
    "pendingQuestion": "Would you like to discuss the hidden costs of your AI project?",
    "contact": "Discuss my project with Qognito",
    "contactStatement": "I would like Qognito to contact me to discuss the profitability and governance of my AI project."
  }
} as const;
