export const whitepaperContent = {
  "fr": {
    "pageTitle": "La facture fantôme de l’IA — Livre blanc Qognito",
    "description": "Supervision humaine, coûts complets, temps réaffecté : examinez les angles morts du ROI de vos projets IA. Un livre blanc pour DG, DAF et DSI.",
    "audience": "LIVRE BLANC · DIRECTIONS GÉNÉRALES, FINANCIÈRES & SI",
    "title": "La facture fantôme de l’IA",
    "lead": "Supervision humaine, coûts complets, temps réellement réaffecté : les trois angles morts du ROI de vos projets IA.",
    "introduction": "Une démonstration impressionnante ne suffit pas à justifier un investissement. Ce livre blanc vous aide à examiner ce que la facture d’API ne montre pas.",
    "download": "Je télécharge le livre blanc",
    "discover": "Je découvre le contenu du livre blanc",
    "coverLabel": "Présentation du livre blanc",
    "benefitsTitle": "Trois questions pour votre prochain comité",
    "question1": "Qui vérifie le résultat ?",
    "answer1": "Rendez visible le travail de relecture, de correction et de supervision que la génération déplace.",
    "question2": "Quel est le coût complet ?",
    "answer2": "Distinguez les dépenses du modèle, l’infrastructure et le travail humain résiduel.",
    "question3": "Que devient le temps gagné ?",
    "answer3": "Évaluez les conditions de réaffectation nécessaires pour produire une valeur économique.",
    "excerptLabel": "EXTRAIT",
    "excerptTitle": "600 € d’API ne sont pas le prix du service",
    "quote": "« Le coût brut de l’inférence face à une masse salariale complète, c’est comparer le prix du kérosène au coût total d’une flotte aérienne. »",
    "example": "Dans le cas pédagogique SAGA, 600 € d’API s’inscrivent dans un coût complet de 16 500 €, dont 12 000 € de travail humain. Ces montants sont des hypothèses de simulation, pas une moyenne observée du marché.",
    "contentsTitle": "Dans le livre blanc",
    "finding": "Le constat :",
    "findingDetail": "le mirage de la délégation totale.",
    "model": "Le modèle :",
    "modelDetail": "les coûts complets et l’impératif de réaffectation.",
    "decision": "La décision :",
    "decisionDetail": "une grille de questions pour examiner votre projet.",
    "authorTitle": "À propos de l’auteur",
    "author": "Boris Guarisma, président de Qognito, accompagne le cadrage et la gouvernance de projets IA. Ce document s’appuie sur les deux sections rédigées du cursus SAGA-IA consacrées au diagnostic et au modèle économique.",
    "preparation": "Le syllabus et les supports de présentation SAGA-IA sont en préparation.",
    "downloadTitle": "Recevez votre accès au PDF",
    "pendingTitle": "Le PDF est en préparation",
    "emailNotice": "Seul l’email est obligatoire. Aucune inscription automatique à une newsletter.",
    "details": "Vos coordonnées",
    "name": "Nom",
    "company": "Entreprise",
    "role": "Fonction",
    "optional": "(facultatif)",
    "privacy": "QOGNITO utilise vos coordonnées pour gérer votre demande et, si vous le souhaitez, vous recontacter. La demande transite par Web3Forms vers notre messagerie.",
    "privacyLink": "Finalités, conservation et exercice de vos droits",
    "nojs": "Activez JavaScript pour utiliser le formulaire, ou demandez le document à",
    "successTitle": "Votre demande a été transmise.",
    "successText": "Vous pouvez maintenant télécharger le livre blanc.",
    "downloadPdf": "Je télécharge mon PDF",
    "followup": "Une question sur votre projet ?",
    "emailQuestion": "Je pose ma question par email",
    "pending": "La version à télécharger sera disponible ici prochainement.",
    "pendingQuestion": "Vous souhaitez échanger sur les coûts cachés de votre projet IA ?",
    "contact": "Je prends contact avec Qognito",
    "contactStatement": "Je souhaite être contacté par Qognito pour échanger sur la rentabilité et la gouvernance de mon projet IA.",
    "coverLines": [
      "La facture",
      "fantôme",
      "de l’IA"
    ],
    "coverTagline": [
      "Du temps gagné",
      "à la valeur démontrée."
    ],
    "coverEyebrow": "QOGNITO · LIVRE BLANC",
    "pdfLanguage": "PDF en français."
  },
  "en": {
    "pageTitle": "The AI Costs You Don’t See — Qognito White Paper",
    "description": "Human oversight, total costs and reallocated time: examine the blind spots in your AI projects’ ROI. A white paper for CEOs, CFOs and CIOs.",
    "audience": "WHITE PAPER · CEOs, CFOs & CIOs",
    "title": "The AI Costs You Don’t See",
    "lead": "Human oversight, total costs and time actually reallocated: three blind spots in your AI projects’ ROI.",
    "introduction": "An impressive demo is not enough to justify an investment. This white paper helps you examine what the API bill leaves out.",
    "download": "Get my white paper",
    "discover": "Show me what’s inside",
    "coverLabel": "White paper cover",
    "benefitsTitle": "Three questions for your next decision meeting",
    "question1": "Who checks the result?",
    "answer1": "Make visible the review, correction and oversight work that AI generation shifts to people.",
    "question2": "What is the total cost?",
    "answer2": "Distinguish model spending, infrastructure costs and the human work that remains.",
    "question3": "What happens to the time saved?",
    "answer3": "Assess how saved time needs to be reallocated to create economic value.",
    "excerptLabel": "EXCERPT",
    "excerptTitle": "€600 in API costs is not the cost of the service",
    "quote": "“Comparing the raw cost of inference with a full payroll bill is like comparing the price of jet fuel with the total cost of an airline fleet.”",
    "example": "In the SAGA teaching case, €600 in API costs sits within a total cost of €16,500, including €12,000 in human work. These figures are simulation assumptions, not observed market averages.",
    "contentsTitle": "Inside the white paper",
    "finding": "The finding:",
    "findingDetail": "the illusion of total delegation.",
    "model": "The model:",
    "modelDetail": "total costs and the need to reallocate saved time.",
    "decision": "The decision:",
    "decisionDetail": "a set of questions to assess your project.",
    "authorTitle": "About the author",
    "author": "Boris Guarisma, president of Qognito, supports the scoping and governance of AI projects. This document draws on the two completed sections of the SAGA-IA course covering diagnosis and the economic model.",
    "preparation": "The SAGA-IA syllabus and presentation materials are in preparation.",
    "downloadTitle": "Get access to the PDF",
    "pendingTitle": "The PDF is in preparation",
    "emailNotice": "Only your email address is required. You will not be automatically subscribed to a newsletter.",
    "details": "Your details",
    "name": "Name",
    "company": "Company",
    "role": "Job title",
    "optional": "(optional)",
    "privacy": "QOGNITO uses your details to handle your request and, if you choose, contact you. Your request passes through Web3Forms to our email service.",
    "privacyLink": "Purposes, retention and your rights (in French)",
    "nojs": "Enable JavaScript to use this form, or request the document by emailing",
    "successTitle": "Your request has been submitted.",
    "successText": "You can now download the white paper.",
    "downloadPdf": "I'm downloading the PDF",
    "followup": "Have a question about your project?",
    "emailQuestion": "Send my question by email",
    "pending": "The downloadable version will be available here soon.",
    "pendingQuestion": "Would you like to discuss the hidden costs of your AI project?",
    "contact": "Discuss my project with Qognito",
    "contactStatement": "I would like Qognito to contact me to discuss the profitability and governance of my AI project.",
    "coverLines": [
      "The AI Costs",
      "You Don’t",
      "See"
    ],
    "coverTagline": [
      "From time saved",
      "to demonstrated value."
    ],
    "coverEyebrow": "QOGNITO · WHITE PAPER",
    "pdfLanguage": "PDF in English."
  },
  "es": {
    "pageTitle": "La factura fantasma de la IA — Libro blanco de Qognito",
    "description": "Supervisión humana, costos completos y tiempo reasignado: examine los puntos ciegos del ROI de sus proyectos de IA. Un libro blanco para la dirección general, financiera y de sistemas.",
    "audience": "LIBRO BLANCO · DIRECCIÓN GENERAL, FINANCIERA Y DE SISTEMAS",
    "title": "La factura fantasma de la IA",
    "lead": "Supervisión humana, costos completos y tiempo realmente reasignado: tres puntos ciegos del ROI de sus proyectos de IA.",
    "introduction": "Una demostración impresionante no basta para justificar una inversión. Este libro blanco le ayuda a examinar lo que no muestra la factura de API.",
    "download": "Descargar el libro blanco",
    "discover": "Ver el contenido del libro blanco",
    "coverLabel": "Presentación del libro blanco",
    "benefitsTitle": "Tres preguntas para su próximo comité de decisión",
    "question1": "¿Quién verifica el resultado?",
    "answer1": "Haga visible el trabajo de revisión, corrección y supervisión que la generación traslada a las personas.",
    "question2": "¿Cuál es el costo total?",
    "answer2": "Distinga el gasto del modelo, la infraestructura y el trabajo humano que sigue siendo necesario.",
    "question3": "¿Qué ocurre con el tiempo ahorrado?",
    "answer3": "Evalúe las condiciones de reasignación necesarias para generar valor económico.",
    "excerptLabel": "EXTRACTO",
    "excerptTitle": "600 € en API no son el costo del servicio",
    "quote": "«Comparar el costo bruto de la inferencia con una masa salarial completa es como comparar el precio del combustible de aviación con el costo total de una flota aérea».",
    "example": "En el caso didáctico SAGA, 600 € en API forman parte de un costo total de 16 500 €, incluidos 12 000 € de trabajo humano. Estas cifras son hipótesis de simulación, no una media observada del mercado.",
    "contentsTitle": "Contenido del libro blanco",
    "finding": "El diagnóstico:",
    "findingDetail": "el espejismo de la delegación total.",
    "model": "El modelo:",
    "modelDetail": "los costos completos y la necesidad de reasignar el tiempo liberado.",
    "decision": "La decisión:",
    "decisionDetail": "una guía de preguntas para examinar su proyecto.",
    "authorTitle": "Sobre el autor",
    "author": "Boris Guarisma, presidente de Qognito, acompaña la definición del alcance y la gobernanza de proyectos de IA. Este documento se basa en las dos secciones redactadas del programa SAGA-IA dedicadas al diagnóstico y al modelo económico.",
    "preparation": "El programa y los materiales de presentación de SAGA-IA están en preparación.",
    "downloadTitle": "Acceda al PDF",
    "pendingTitle": "El PDF está en preparación",
    "emailNotice": "Solo es obligatorio indicar el correo electrónico. No se le suscribirá automáticamente a un boletín.",
    "details": "Sus datos",
    "name": "Nombre",
    "company": "Empresa",
    "role": "Cargo",
    "optional": "(opcional)",
    "privacy": "QOGNITO utiliza sus datos para gestionar su solicitud y, si así lo desea, ponerse en contacto con usted. La solicitud se transmite a través de Web3Forms a nuestro servicio de correo electrónico.",
    "privacyLink": "Finalidades, conservación y ejercicio de sus derechos",
    "nojs": "Active JavaScript para utilizar el formulario o solicite el documento por correo electrónico a",
    "successTitle": "Su solicitud se ha enviado.",
    "successText": "Ya puede descargar el libro blanco.",
    "downloadPdf": "Descargar el PDF",
    "followup": "¿Tiene alguna pregunta sobre su proyecto?",
    "emailQuestion": "Enviar mi pregunta por correo electrónico",
    "pending": "La versión descargable estará disponible aquí próximamente.",
    "pendingQuestion": "¿Quiere hablar sobre los costos ocultos de su proyecto de IA?",
    "contact": "Contactar con Qognito",
    "contactStatement": "Quiero que Qognito se ponga en contacto conmigo para hablar sobre la rentabilidad y la gobernanza de mi proyecto de IA.",
    "coverLines": ["La factura", "fantasma", "de la IA"],
    "coverTagline": ["Del tiempo liberado", "al valor demostrado."],
    "coverEyebrow": "QOGNITO · LIBRO BLANCO",
    "pdfLanguage": "PDF en español."
  }
} as const;
